-- upgrade-v5.8-exploration-rooms.sql
-- 목적: 탐사 홈페이지 1차 실사용판용 방/참가자/상태/채팅 테이블과 RPC를 추가한다.
-- 전제: v5.3~v5.7 패치가 적용되어 profiles에 character_key/organization_code/department_code/affiliation_label이 존재한다.
-- 주의: service_role key, DB password, JWT secret은 프론트엔드/GitHub에 넣지 않는다.

create table if not exists public.exploration_rooms (
  id uuid primary key default gen_random_uuid(),
  scenario_id text not null,
  title text not null,
  host_user_id uuid not null references public.profiles(id) on delete cascade,
  invite_code text not null unique,
  max_players integer not null default 2 check (max_players between 1 and 4),
  status text not null default 'waiting' check (status in ('waiting', 'playing', 'ended')),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  ended_at timestamptz
);

create table if not exists public.exploration_room_members (
  room_id uuid not null references public.exploration_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'player' check (role in ('host', 'player', 'observer')),
  character_key_snapshot text,
  display_name_snapshot text not null default '익명',
  organization_code_snapshot text not null default 'unaffiliated',
  department_code_snapshot text not null default 'none',
  affiliation_label_snapshot text not null default '무소속',
  visitor_type_snapshot text not null default 'human',
  pollution_snapshot integer not null default 0,
  mask_collapse_rate_snapshot integer not null default 0,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  primary key (room_id, user_id),
  constraint exploration_room_members_org_check check (organization_code_snapshot in ('baekildream', 'disaster_agency', 'entity', 'unaffiliated', 'other')),
  constraint exploration_room_members_dept_check check (department_code_snapshot in ('field_exploration', 'research', 'security', 'agent', 'entity', 'none', 'other')),
  constraint exploration_room_members_visitor_check check (visitor_type_snapshot in ('human', 'infected', 'entity'))
);

create table if not exists public.exploration_room_state (
  room_id uuid primary key references public.exploration_rooms(id) on delete cascade,
  current_section_key text not null default 'intro',
  state_json jsonb not null default '{}'::jsonb,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.exploration_room_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.exploration_rooms(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  sender_display_name text not null default '익명',
  message_type text not null default 'normal' check (message_type in ('normal', 'system', 'dice', 'item', 'whisper')),
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists exploration_rooms_host_idx on public.exploration_rooms(host_user_id, created_at desc);
create index if not exists exploration_rooms_invite_code_idx on public.exploration_rooms(invite_code);
create index if not exists exploration_room_members_user_idx on public.exploration_room_members(user_id, joined_at desc);
create index if not exists exploration_room_members_room_idx on public.exploration_room_members(room_id, joined_at);
create index if not exists exploration_room_messages_room_created_idx on public.exploration_room_messages(room_id, created_at);

alter table public.exploration_rooms enable row level security;
alter table public.exploration_room_members enable row level security;
alter table public.exploration_room_state enable row level security;
alter table public.exploration_room_messages enable row level security;

create or replace function public.is_exploration_room_member(p_room_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.exploration_room_members m
    where m.room_id = p_room_id
      and m.user_id = auth.uid()
      and m.left_at is null
  );
$$;

grant execute on function public.is_exploration_room_member(uuid) to authenticated;

create or replace function public.is_exploration_room_host(p_room_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.exploration_rooms r
    where r.id = p_room_id
      and r.host_user_id = auth.uid()
  );
$$;

grant execute on function public.is_exploration_room_host(uuid) to authenticated;

-- RLS: 방 구성원만 자기 방을 볼 수 있다. 방 입장은 join RPC가 초대코드로 처리한다.
drop policy if exists "Exploration members can read their rooms" on public.exploration_rooms;
create policy "Exploration members can read their rooms"
on public.exploration_rooms
for select
to authenticated
using (public.is_exploration_room_member(id) or public.is_admin());

drop policy if exists "Exploration members can read room members" on public.exploration_room_members;
create policy "Exploration members can read room members"
on public.exploration_room_members
for select
to authenticated
using (public.is_exploration_room_member(room_id) or public.is_admin());

drop policy if exists "Exploration members can read room state" on public.exploration_room_state;
create policy "Exploration members can read room state"
on public.exploration_room_state
for select
to authenticated
using (public.is_exploration_room_member(room_id) or public.is_admin());

drop policy if exists "Exploration members can read room messages" on public.exploration_room_messages;
create policy "Exploration members can read room messages"
on public.exploration_room_messages
for select
to authenticated
using (public.is_exploration_room_member(room_id) or public.is_admin());

-- 클라이언트 직접 insert/update/delete는 열지 않는다. 방 생성/입장/진행/채팅은 RPC로만 수행한다.

grant select on public.exploration_rooms to authenticated;
grant select on public.exploration_room_members to authenticated;
grant select on public.exploration_room_state to authenticated;
grant select on public.exploration_room_messages to authenticated;

grant usage, select on sequence public.exploration_room_messages_id_seq to authenticated;

create or replace function public.create_exploration_room(
  p_scenario_id text,
  p_title text,
  p_max_players integer default 2,
  p_start_section_key text default 'intro',
  p_state_json jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
  v_room public.exploration_rooms;
  v_invite_code text;
  v_try integer := 0;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  select * into v_profile
  from public.profiles
  where id = auth.uid();

  if v_profile.id is null then
    raise exception '프로필을 찾을 수 없습니다.';
  end if;

  if coalesce(v_profile.status, 'active') <> 'active' then
    raise exception '활성 상태의 계정만 탐사방을 만들 수 있습니다.';
  end if;

  if p_max_players is null or p_max_players < 1 or p_max_players > 4 then
    raise exception '최대 인원은 1~4명 사이여야 합니다.';
  end if;

  loop
    v_try := v_try + 1;
    v_invite_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
    exit when not exists (select 1 from public.exploration_rooms where invite_code = v_invite_code);
    if v_try > 20 then
      raise exception '초대코드 생성에 실패했습니다.';
    end if;
  end loop;

  insert into public.exploration_rooms (
    scenario_id,
    title,
    host_user_id,
    invite_code,
    max_players,
    status
  ) values (
    coalesce(nullif(trim(p_scenario_id), ''), 'unknown'),
    coalesce(nullif(trim(p_title), ''), '이름 없는 탐사방'),
    auth.uid(),
    v_invite_code,
    p_max_players,
    'waiting'
  ) returning * into v_room;

  insert into public.exploration_room_members (
    room_id,
    user_id,
    role,
    character_key_snapshot,
    display_name_snapshot,
    organization_code_snapshot,
    department_code_snapshot,
    affiliation_label_snapshot,
    visitor_type_snapshot,
    pollution_snapshot,
    mask_collapse_rate_snapshot
  ) values (
    v_room.id,
    auth.uid(),
    'host',
    v_profile.character_key,
    coalesce(nullif(trim(v_profile.display_name), ''), '익명'),
    coalesce(nullif(trim(v_profile.organization_code), ''), 'unaffiliated'),
    coalesce(nullif(trim(v_profile.department_code), ''), 'none'),
    coalesce(nullif(trim(v_profile.affiliation_label), ''), '무소속'),
    coalesce(nullif(trim(v_profile.visitor_type), ''), 'human'),
    coalesce(v_profile.pollution, 0),
    coalesce(v_profile.mask_collapse_rate, 0)
  );

  insert into public.exploration_room_state (
    room_id,
    current_section_key,
    state_json,
    updated_by
  ) values (
    v_room.id,
    coalesce(nullif(trim(p_start_section_key), ''), 'intro'),
    coalesce(p_state_json, '{}'::jsonb),
    auth.uid()
  );

  insert into public.exploration_room_messages (
    room_id,
    sender_id,
    sender_display_name,
    message_type,
    content
  ) values (
    v_room.id,
    auth.uid(),
    '시스템',
    'system',
    '탐사방이 생성되었습니다.'
  );

  return jsonb_build_object(
    'ok', true,
    'room_id', v_room.id,
    'invite_code', v_room.invite_code,
    'status', v_room.status
  );
end;
$$;

grant execute on function public.create_exploration_room(text, text, integer, text, jsonb) to authenticated;

create or replace function public.join_exploration_room(p_invite_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
  v_room public.exploration_rooms;
  v_member_count integer;
  v_existing public.exploration_room_members;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  select * into v_profile
  from public.profiles
  where id = auth.uid();

  if v_profile.id is null then
    raise exception '프로필을 찾을 수 없습니다.';
  end if;

  if coalesce(v_profile.status, 'active') <> 'active' then
    raise exception '활성 상태의 계정만 탐사방에 들어갈 수 있습니다.';
  end if;

  select * into v_room
  from public.exploration_rooms
  where invite_code = upper(trim(p_invite_code))
  for update;

  if v_room.id is null then
    raise exception '초대코드가 올바르지 않습니다.';
  end if;

  if v_room.status = 'ended' then
    raise exception '이미 종료된 탐사방입니다.';
  end if;

  select * into v_existing
  from public.exploration_room_members
  where room_id = v_room.id
    and user_id = auth.uid();

  if v_existing.room_id is not null then
    if v_existing.left_at is not null then
      update public.exploration_room_members
      set left_at = null,
          joined_at = now()
      where room_id = v_room.id
        and user_id = auth.uid();
    end if;

    return jsonb_build_object(
      'ok', true,
      'already_member', true,
      'room_id', v_room.id,
      'invite_code', v_room.invite_code
    );
  end if;

  select count(*) into v_member_count
  from public.exploration_room_members
  where room_id = v_room.id
    and left_at is null;

  if v_member_count >= v_room.max_players then
    raise exception '탐사방 인원이 가득 찼습니다.';
  end if;

  insert into public.exploration_room_members (
    room_id,
    user_id,
    role,
    character_key_snapshot,
    display_name_snapshot,
    organization_code_snapshot,
    department_code_snapshot,
    affiliation_label_snapshot,
    visitor_type_snapshot,
    pollution_snapshot,
    mask_collapse_rate_snapshot
  ) values (
    v_room.id,
    auth.uid(),
    'player',
    v_profile.character_key,
    coalesce(nullif(trim(v_profile.display_name), ''), '익명'),
    coalesce(nullif(trim(v_profile.organization_code), ''), 'unaffiliated'),
    coalesce(nullif(trim(v_profile.department_code), ''), 'none'),
    coalesce(nullif(trim(v_profile.affiliation_label), ''), '무소속'),
    coalesce(nullif(trim(v_profile.visitor_type), ''), 'human'),
    coalesce(v_profile.pollution, 0),
    coalesce(v_profile.mask_collapse_rate, 0)
  );

  insert into public.exploration_room_messages (
    room_id,
    sender_id,
    sender_display_name,
    message_type,
    content
  ) values (
    v_room.id,
    auth.uid(),
    '시스템',
    'system',
    coalesce(nullif(trim(v_profile.display_name), ''), '익명') || ' 님이 탐사방에 입장했습니다.'
  );

  return jsonb_build_object(
    'ok', true,
    'already_member', false,
    'room_id', v_room.id,
    'invite_code', v_room.invite_code
  );
end;
$$;

grant execute on function public.join_exploration_room(text) to authenticated;

create or replace function public.advance_exploration_room(
  p_room_id uuid,
  p_next_section_key text,
  p_choice_label text default null,
  p_state_patch jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_member public.exploration_room_members;
  v_room public.exploration_rooms;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  select * into v_member
  from public.exploration_room_members
  where room_id = p_room_id
    and user_id = auth.uid()
    and left_at is null;

  if v_member.room_id is null then
    raise exception '탐사방 참가자만 진행할 수 있습니다.';
  end if;

  select * into v_room
  from public.exploration_rooms
  where id = p_room_id
  for update;

  if v_room.id is null then
    raise exception '탐사방을 찾을 수 없습니다.';
  end if;

  if v_room.status = 'ended' then
    raise exception '이미 종료된 탐사방입니다.';
  end if;

  if nullif(trim(p_next_section_key), '') is null then
    raise exception '다음 섹션이 비어 있습니다.';
  end if;

  update public.exploration_rooms
  set status = case when status = 'waiting' then 'playing' else status end,
      started_at = case when started_at is null then now() else started_at end
  where id = p_room_id;

  update public.exploration_room_state
  set current_section_key = trim(p_next_section_key),
      state_json = coalesce(state_json, '{}'::jsonb) || coalesce(p_state_patch, '{}'::jsonb),
      updated_by = auth.uid(),
      updated_at = now()
  where room_id = p_room_id;

  insert into public.exploration_room_messages (
    room_id,
    sender_id,
    sender_display_name,
    message_type,
    content
  ) values (
    p_room_id,
    auth.uid(),
    '시스템',
    'system',
    coalesce(v_member.display_name_snapshot, '익명') || ' 님이 선택했습니다: ' || coalesce(nullif(trim(p_choice_label), ''), trim(p_next_section_key))
  );

  return jsonb_build_object('ok', true, 'room_id', p_room_id, 'current_section_key', trim(p_next_section_key));
end;
$$;

grant execute on function public.advance_exploration_room(uuid, text, text, jsonb) to authenticated;

create or replace function public.post_exploration_message(
  p_room_id uuid,
  p_content text,
  p_message_type text default 'normal'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_member public.exploration_room_members;
  v_type text;
  v_content text;
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  select * into v_member
  from public.exploration_room_members
  where room_id = p_room_id
    and user_id = auth.uid()
    and left_at is null;

  if v_member.room_id is null then
    raise exception '탐사방 참가자만 채팅할 수 있습니다.';
  end if;

  v_content := nullif(trim(p_content), '');
  if v_content is null then
    raise exception '메시지가 비어 있습니다.';
  end if;

  if length(v_content) > 500 then
    raise exception '메시지는 500자 이하로 입력하세요.';
  end if;

  v_type := case when p_message_type in ('normal', 'dice', 'item', 'whisper') then p_message_type else 'normal' end;

  insert into public.exploration_room_messages (
    room_id,
    sender_id,
    sender_display_name,
    message_type,
    content
  ) values (
    p_room_id,
    auth.uid(),
    coalesce(v_member.display_name_snapshot, '익명'),
    v_type,
    v_content
  );

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.post_exploration_message(uuid, text, text) to authenticated;

create or replace function public.clear_exploration_room_messages(p_room_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if not (public.is_exploration_room_host(p_room_id) or public.is_admin()) then
    raise exception '방장 또는 관리자만 채팅을 초기화할 수 있습니다.';
  end if;

  delete from public.exploration_room_messages
  where room_id = p_room_id;

  insert into public.exploration_room_messages (
    room_id,
    sender_id,
    sender_display_name,
    message_type,
    content
  ) values (
    p_room_id,
    auth.uid(),
    '시스템',
    'system',
    '채팅 로그가 초기화되었습니다.'
  );

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.clear_exploration_room_messages(uuid) to authenticated;

create or replace function public.leave_exploration_room(p_room_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.';
  end if;

  update public.exploration_room_members
  set left_at = now()
  where room_id = p_room_id
    and user_id = auth.uid();

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.leave_exploration_room(uuid) to authenticated;

-- Realtime 사용. 이미 publication에 들어간 테이블이면 조용히 넘어간다.
do $$
begin
  alter publication supabase_realtime add table public.exploration_room_state;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.exploration_room_messages;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.exploration_room_members;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;
